[project]
name = "devops-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.8",
    "mysqlclient>=2.2.7",
    "python-decouple>=3.8",
]
